export const eventCategories = [
  "Music",
  "Technology",
  "Food & Culinary",
  "Art & Culture",
  "Sports & Fitness",
  "Business & Networking",
  "Education & Learning",
  "Health & Wellness",
  "Entertainment",
  "Fashion & Beauty",
  "Travel & Tourism",
  "Community & Social",
  "Religious & Spiritual",
  "Charity & Fundraising",
  "Kids & Family",
  "Photography",
  "Literature & Books",
  "Gaming & Esports",
  "Science & Innovation",
  "Environment & Nature",
  "Other",
] as const

export const musicSubcategories = [
  "EDM/Electronic",
  "Classical",
  "Rock",
  "Pop",
  "Hip Hop/Rap",
  "Jazz",
  "Blues",
  "Country",
  "Folk",
  "Reggae",
  "Metal",
  "Indie",
  "R&B/Soul",
  "Punk",
  "Alternative",
  "World Music",
  "Traditional/Cultural",
  "Live Band",
  "DJ Set",
  "Concert",
  "Festival",
  "Other",
] as const

export const sriLankanDistricts = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya",
] as const

export type EventCategory = (typeof eventCategories)[number]
export type MusicSubcategory = (typeof musicSubcategories)[number]
export type SriLankanDistrict = (typeof sriLankanDistricts)[number]
