-- Insert sample events with proper geographic coordinates
INSERT INTO public.events (
  title, description, date, time, venue, location, address, city, category, 
  price, max_attendees, image_url, latitude, longitude, featured, user_id
) VALUES 
-- Music Events
(
  'Colombo Music Festival 2024',
  'Join us for an amazing night of local and international music acts featuring the best of Sri Lankan and world music. Experience live performances from renowned artists in a spectacular outdoor setting.',
  '2024-12-20',
  '18:00',
  'Galle Face Green',
  'Colombo',
  'Galle Face Green, Colombo 03',
  'Colombo',
  'Music',
  2500.00,
  2000,
  '/placeholder.svg?height=300&width=400',
  6.9271,
  79.8612,
  true,
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Jazz Night at Mount Lavinia',
  'An intimate evening of smooth jazz by the beach. Featuring local jazz musicians and international guest artists.',
  '2024-12-25',
  '19:30',
  'Mount Lavinia Hotel',
  'Mount Lavinia',
  'Hotel Road, Mount Lavinia',
  'Mount Lavinia',
  'Music',
  3500.00,
  150,
  '/placeholder.svg?height=300&width=400',
  6.8344,
  79.8631,
  true,
  (SELECT id FROM auth.users LIMIT 1)
),

-- Technology Events
(
  'Tech Meetup Kandy',
  'Networking and knowledge sharing for tech enthusiasts. Topics include AI, blockchain, and mobile development. Perfect for developers, entrepreneurs, and tech students.',
  '2024-12-18',
  '14:00',
  'University of Peradeniya',
  'Kandy',
  'University Park, Peradeniya',
  'Kandy',
  'Technology',
  0.00,
  200,
  '/placeholder.svg?height=300&width=400',
  7.2906,
  80.6337,
  false,
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Startup Pitch Competition',
  'Watch innovative startups pitch their ideas to a panel of investors and industry experts. Network with entrepreneurs and learn about the latest trends.',
  '2024-12-28',
  '09:00',
  'Colombo Stock Exchange',
  'Colombo',
  'Tower 1, World Trade Center, Echelon Square',
  'Colombo',
  'Business',
  1000.00,
  300,
  '/placeholder.svg?height=300&width=400',
  6.9319,
  79.8478,
  true,
  (SELECT id FROM auth.users LIMIT 1)
),

-- Food Events
(
  'Food Festival Galle',
  'Taste the best of Sri Lankan cuisine and international flavors. Over 50 food stalls, cooking demonstrations, and cultural performances.',
  '2024-12-22',
  '10:00',
  'Galle Fort',
  'Galle',
  'Church Street, Galle Fort',
  'Galle',
  'Food',
  1500.00,
  1000,
  '/placeholder.svg?height=300&width=400',
  6.0329,
  80.2170,
  true,
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Street Food Tour Negombo',
  'Explore the authentic street food scene of Negombo with local guides. Taste traditional snacks, fresh seafood, and tropical fruits.',
  '2024-12-30',
  '16:00',
  'Negombo Fish Market',
  'Negombo',
  'Lellama Road, Negombo',
  'Negombo',
  'Food',
  2000.00,
  50,
  '/placeholder.svg?height=300&width=400',
  7.2083,
  79.8358,
  false,
  (SELECT id FROM auth.users LIMIT 1)
),

-- Art & Culture Events
(
  'Art Exhibition Negombo',
  'Contemporary Sri Lankan art by emerging artists. Featuring paintings, sculptures, and digital art exploring themes of identity and culture.',
  '2024-12-19',
  '09:00',
  'Negombo Cultural Center',
  'Negombo',
  'Main Street, Negombo',
  'Negombo',
  'Art',
  500.00,
  200,
  '/placeholder.svg?height=300&width=400',
  7.2083,
  79.8358,
  false,
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Traditional Dance Performance',
  'Experience the rich cultural heritage of Sri Lanka through traditional Kandyan and low-country dance performances.',
  '2024-12-26',
  '19:00',
  'Nelum Pokuna Theatre',
  'Colombo',
  'Nelum Pokuna Mahinda Rajapaksa Theatre',
  'Colombo',
  'Culture',
  1200.00,
  500,
  '/placeholder.svg?height=300&width=400',
  6.9147,
  79.8731,
  true,
  (SELECT id FROM auth.users LIMIT 1)
),

-- Sports Events
(
  'Beach Volleyball Tournament',
  'Annual beach volleyball championship featuring teams from across the island. Open to all skill levels with separate categories.',
  '2024-12-29',
  '08:00',
  'Unawatuna Beach',
  'Galle',
  'Unawatuna Beach Road',
  'Galle',
  'Sports',
  800.00,
  100,
  '/placeholder.svg?height=300&width=400',
  6.0108,
  80.2506,
  false,
  (SELECT id FROM auth.users LIMIT 1)
),

-- Health & Wellness Events
(
  'Yoga Retreat Ella',
  'A peaceful weekend yoga retreat in the hills of Ella. Includes meditation sessions, healthy meals, and nature walks.',
  '2024-12-21',
  '06:00',
  'Ella Rock Resort',
  'Ella',
  'Ella Rock, Ella',
  'Ella',
  'Health',
  4500.00,
  30,
  '/placeholder.svg?height=300&width=400',
  6.8667,
  81.0500,
  true,
  (SELECT id FROM auth.users LIMIT 1)
);
